### PR TITLE
Dismissed keyboard on tap

### PR DESCRIPTION
**Pull request by sangameshsomawar**
Fixed: https://github.com/bigbinary/neeto-ui-rn/issues/476

### CODE REVIEW

**Comment by sangameshsomawar** [comment]
[Implementation and Demo](https://user-images.githubusercontent.com/93119254/189317969-aaeff505-604b-461c-96ef-e5a8d524252e.webm)

**Comment by injas-bigbinary** [comment]
@sangameshsomawar We can make it `true` by default IMO. in most of the cases we are handling it manually, there might be a tiny chance of keeping the keyboard active when tapped outside and in that case, we can make it `false` through props.

**Comment by souravbaranwal** [comment]
@sangameshsomawar I believe both are fine. But there will be a lot of places where there won't be any forms, with that in mind we should be going for `false` as the default value.

**Comment by sangameshsomawar** [comment]
@injas-bigbinary @souravbaranwal  we got 1-1 vote for default true and false. Let's hear from others as well. 😅

My vote is more towards keeping it false by default. Still not sure 😅

**Comment by Tsudhishnair** [comment]
@sangameshsomawar  I think we can keep this as `true` as we are only dismissing the keyboard only when the keyboard is open and when the touch even target is not an InputText. Even if there aren't any InputText in a particular screen keeping this prop as `true` won't have any effect right as the keyboard won't be open in the first place itself.

**Comment by kamolesh97** [comment]
My vote goes to keeping as ```true``` by default as well.

**Comment by jenipharachel** [comment]
@sangameshsomawar LGTM. Merging this PR

**Pull request merged**
