### PR TITLE
Custom input accessory view for multiline input

### PR DESCRIPTION
**Pull request by sangameshsomawar**

### CODE REVIEW

**Comment by sangameshsomawar** [comment]
@bigbinary/neeto-rn Tried to fix the user experience issue for multiline inputs, let me know if you have any other ideas to "defocus multiline input".

https://user-images.githubusercontent.com/93119254/183296984-9e5eef26-2dff-4d7d-a4c3-98946ab9f327.mp4

**Comment by injas-bigbinary** [comment]
@sangameshsomawar looks good.

**Comment by sangameshsomawar** [comment]
@jenipharachel _A Please test in android.

**Comment by jenipharachel** [comment]
@sangameshsomawar _a https://www.reddit.com/r/reactnative/comments/dvgdct/inputaccessoryview_for_android/?utm_source=share&utm_medium=web2x&context=3

>InputAccessoryView
>
>A component which enables customization of the keyboard input accessory view on iOS.

Screenshot 2022-08-10 at 5 45 00 PM

**Comment by sangameshsomawar** [comment]
@jenipharachel can you check how defocus happens in android?

**Comment by jenipharachel** [comment]
@sangameshsomawar In android, WhatsApp has search only in the chat list screen. Not in the conversation screen.

https://user-images.githubusercontent.com/35962711/183902357-6545de31-dc39-4a8a-b2a0-b1faea2a53c5.mp4

**Comment by jenipharachel** [comment]
@sangameshsomawar Please check this as well. https://youtu.be/vBbmr8uCeFs

**Comment by sangameshsomawar** [comment]
@jenipharachel _a Rendering in iOS only as of now, Pushed the change, Please review and merge.

**Comment by jenipharachel** [comment]
LGTM. Merging!

**Pull request merged**
