### PR TITLE
Fix Button: make label prop optional

### LINKED ISSUE #655: Fix Button: make the label as an optional prop
> We can make the label as an optional prop in the Button component because we need to use the button without `label` as well.

_Originally posted by @paulsojan in https://github.com/bigbinary/neeto-cal-rn/issues/453#issuecomment-2114278541_

### PR DESCRIPTION
**Pull request by shashank-bhatotia**
- Fixes #655

### CODE REVIEW

**Comment by shashank-bhatotia** [comment]
@paulsojan _a Please review.

**Review by paulsojan — APPROVED** [review]

**Comment by paulsojan** [comment]
@sangameshsomawar _a Please review and merge

**Review by sangameshsomawar — APPROVED** [review]
@paulsojan @shashank-bhatotia : If we are using a button without a label, are we using it with an icon? If so, I think we need to adjust the margins when the label is empty. Otherwise, the icon might appear misaligned. Please check this scenario and merge.

Screenshot 2024-05-16 at 1 58 02 PM

**Comment by shashank-bhatotia** [comment]
@sangameshsomawar _a Please review

**Pull request merged**
