### PR TITLE
exported ref and state change callback

### PR DESCRIPTION
**Pull request by injas-bigbinary**
@sangameshsomawar _a
Cc: @Tsudhishnair

### CODE REVIEW

**Review by sangameshsomawar — APPROVED** [review]
@injas-bigbinary  @Tsudhishnair  Let me know your thoughts on naming conventions. 


```

      <Container py={2}>
        <Typography py={2}>Accordion controlled via ref</Typography>
        <Button label="Expand / Shrink" onPress={() => {
          ref.current.handleAccordion()
        }} />
        <Accordion
          ref={ref}
          // eslint-disable-next-line no-unused-vars
          onAccordionStateChanged={isExpanded => { }}
          iconProp={{
            Label: () => <Typography color="font.danger">Accordion</Typography>,
            color: theme.colors.font.danger,
          }}
          noBorder={true}
        >
          <Container my={2} p={3} bg="background.grey100" borderRadius={8}>
            <Typography color="font.primary">Body Content</Typography>
          </Container>
        </Accordion>
      </Container>
```
https://user-images.githubusercontent.com/93119254/182841785-d266c4d8-bc83-4a34-95aa-02f32e200c86.mp4


https://user-images.githubusercontent.com/93119254/182841809-338af690-85cb-4a0a-855a-9275d4947c25.mp4

**Comment by injas-bigbinary** [comment]
@sangameshsomawar _a Updated

https://user-images.githubusercontent.com/87293196/182850140-eb6a3587-192f-47dc-b067-540e337cd8ae.mp4

**Comment by sangameshsomawar** [comment]
@injas-bigbinary LGTM, @Tsudhishnair _a Please review.

**Comment by Tsudhishnair** [comment]
LGTM.

**Pull request merged**
