### PR TITLE
Implemented Fuse JS for handling the search

### PR DESCRIPTION
**Pull request by injas-bigbinary**
Now `BottomSheet` `onItemPress` will return index and item
```
onItemPress={({ index , item}) => {
}}
```
`ContentRow` now returns the `item` prop with the original item in it and renamed `id` prop to `index`

```
ContentRow={({ item, bg, onPress, isSelected }) => {
}}
```

@bigbinary/neeto-rn  Need to make these changes when updating to the latest version

### CODE REVIEW

**Comment by injas-bigbinary** [comment]
@sangameshsomawar _a Please check

**Comment by injas-bigbinary** [comment]
https://user-images.githubusercontent.com/87293196/183848504-72da9cb0-e68f-4b95-8cfa-60ff6298929d.mp4

**Review by sangameshsomawar — APPROVED** [review]
@injas-bigbinary Looks good to me.

Found this minor issue, we should trim before searching.

Screenshot 2022-08-10 at 5 21 18 PM


@jenipharachel _a Please review as well.

**Comment by jenipharachel** [comment]
@injas-bigbinary @sangameshsomawar  Except the position of Done button. Rest looks good.

Screenshot 2022-08-10 at 8 01 05 PM

**Comment by sangameshsomawar** [comment]
@jenipharachel yes same I thought but where else we can put it 😅

**Comment by jenipharachel** [comment]
@sangameshsomawar Can't we ask @KiranRaj7 ?

**Comment by KiranRaj7** [comment]
I will make a solution soon😆
@sangameshsomawar @jenipharachel @injas-bigbinary

**Comment by KiranRaj7** [comment]
Actually the search in bottom sheet of project selection (neetoInvoice) is a single option variant. So it doesn't need 'Done' CTA. But this similar case occur in neetoPlanner multi member selection, so here I placed the search as full width component as in the image. So in case of 'multi option with search' bottom sheet I think we need to do this way for keeping things aligned. 
image

@sangameshsomawar @jenipharachel @injas-bigbinary

**Comment by injas-bigbinary** [comment]
@KiranRaj7 @sangameshsomawar @jenipharachel Which one is better? Should I try any other option? 

https://user-images.githubusercontent.com/87293196/184075705-bde892b6-21be-4e5a-a8eb-16c2f3458ebc.mp4


https://user-images.githubusercontent.com/87293196/184075855-0638ebb4-bcb6-43e9-9d58-f71cd73f6d2d.mp4

**Comment by sangameshsomawar** [comment]
@injas-bigbinary

1. I think technically we cannot go with first option as done is always needed. 
2. We can go with the second option, and conditionally show the search bar based on the prop. Because we might not need a search bar in some cases.

**Comment by KiranRaj7** [comment]
1. Yes done is always need in 'Multi Option' but if it was 'Single Option' it suits.
2. This one is much universal for all kinds of bottom sheet with Search.

@injas-bigbinary @sangameshsomawar

**Comment by injas-bigbinary** [comment]
@sangameshsomawar The search bar is shown if `canSearch` is set, but there won't be a separate button to show the search bar. If `canSearch` is set then the search bar will be always shown. Added prop to hide the cancel button in `SearchBar` component. If we need an option to show the search bar within the bottom sheet on user interaction, we should keep the lens icon which will be similar to the already existing design.

**Comment by sangameshsomawar** [comment]
@injas-bigbinary I think we can directly show search bar if  `canSearch ` is true and no need to show the cancel button I think.

**Comment by injas-bigbinary** [comment]
@sangameshsomawar Updated

**Review by jenipharachel — COMMENTED** [review]
@injas-bigbinary Can we remove this padding as well? It is causing extra space in neetoChat. Just check if removing that space is affecting other components

**Review by jenipharachel — CHANGES_REQUESTED** [review]
Meant this one https://github.com/bigbinary/neeto-ui-rn/blob/ac1a6f27d0f1f6d718049838aa52e3a5645fb072/src/components/BottomSheet.js#L37

**Comment by injas-bigbinary** [comment]
@jenipharachel Can be removed by passing style to `titleContainerStyle` prop. Can you try that way?

**Review by jenipharachel — APPROVED** [review]

**Review by sangameshsomawar — APPROVED** [review]
@injas-bigbinary Looks good to me as well, Merging this PR.

@Tsudhishnair Please implement in neetoDesk and lets see how it goes.

**Pull request merged**
