### PR TITLE
Accordion Component Implementation 

### LINKED ISSUE #298: Accordion Component
https://www.figma.com/file/GvxNW24y6lmKkrzdZCIz2e/Design-System?node-id=447%3A1382

### PR DESCRIPTION
**Pull request by Tsudhishnair**
Fixes #298 

**Preview**
Screenshot 2022-07-22 at 2 33 22 PM
Screenshot 2022-07-22 at 2 33 28 PM

### CODE REVIEW

**Comment by Tsudhishnair** [comment]
@sangameshsomawar _a Please review.

**Comment by Tsudhishnair** [comment]
@sangameshsomawar I have tried making the component as generic as possible still trying to keep the code minimal. Currently its seems like all the use we have like in neetoDesk and in neetoInvoice where we need the accordion can be achieved from this component itself.

**Review by sangameshsomawar — APPROVED** [review]
@Tsudhishnair  _a Let me know your thoughts.

https://user-images.githubusercontent.com/93119254/180449548-e26b066b-7ec2-4307-85e7-328b637bd458.mp4

```import React, { useContext, useRef, useState } from "react";
import { Animated } from "react-native";
import PropTypes from "prop-types";
import Icon from "react-native-remix-icon";
import { ThemeContext } from "styled-components/native";

import { Container, Touchable } from "@components";

/**
 * A component used to display an expandable list item.
 *
 *  ## Usage
 * ```js
 * import * as React from 'react';
 * import { Container, Accordion } from '@bigbinary/neetoui-rn';
 *
 * export default function Main() {
 *  return (
 *    <Container>
 *     <Accordion
 *         Header={() => (
 *           <Container flexDirection="row" alignItems="center">
 *             <Typography bg="#00BA8829" color="font.green800" p={1}>
 *               Open
 *             </Typography>
 *             <Typography px={2}>Low</Typography>
 *           </Container>
 *         )}
 *         iconProp={{
 *           IconLabel: () => (
 *             <Typography color="font.danger">Collapse</Typography>
 *           ),
 *           iconColor: theme.colors.font.danger,
 *         }}
 *       >
 *         <Container my={2} p={3} bg="background.grey100" borderRadius={8}>
 *           <Typography color="font.primary">Body Content</Typography>
 *         </Container>
 *       </Accordion>
 *    </Container>
 *  );
 * }
 * ```
 *
 */

export const Accordion = props => {
  const { Header, noBorder = false, iconProp = {}, children } = props;
  const { iconName, IconLabel, iconSize, iconColor } = iconProp;
  const theme = useContext(ThemeContext);
  const [isExpanded, setExpanded] = useState(false);
  const [viewHeight, setViewHeight] = useState(0);
  const animationController = useRef(
    new Animated.Value(isExpanded ? 1 : 0)
  ).current;

  const getLayout = event => {
    const height = event.nativeEvent.layout.height;
    setViewHeight(height);
  };

  const handleAnimation = () => {
    Animated.timing(animationController, {
      duration: 300,
      toValue: isExpanded ? 1 : 0,
      useNativeDriver: false,
    }).start();
    setExpanded(!isExpanded);
  };

  const arrowAngle = animationController.interpolate({
    inputRange: [0, 1],
    outputRange: ["0rad", `${Math.PI}rad`],
  });

  const bodyContentHeight = animationController.interpolate({
    inputRange: [0, 1],
    outputRange: [0, viewHeight],
  });

  return (
    <Container
      {...(!noBorder && {
        borderColor: "border.grey400",
        borderWidth: 1,
        borderRadius: 8,
      })}
      width="100%"
    >
      <Touchable p={2} flexDirection="row" alignItems="center" onPress={() => {
        handleAnimation();
      }}>
        {!!Header && (
          <Container flexGrow={1}>
            <Header />
          </Container>
        )}
        <Container
          alignItems="center"
          justifyContent="center"
          flexDirection="row"
          px={1}
        >
          {IconLabel && <IconLabel />}
          <Animated.View
            style={{
              alignItems: "flex-end",
              transform: [{ rotateZ: arrowAngle }],
            }}
          >
            <Container>
              <Icon
                name={iconName ?? "ri-arrow-down-s-line"}
                color={iconColor ?? theme.colors.font.grey700}
                size={iconSize ?? 24}
              />
            </Container>
          </Animated.View>
        </Container>
      </Touchable>
      <Animated.View style={{ height: bodyContentHeight, overflow: "hidden" }}>
        <Container width="100%" position="absolute" onLayout={getLayout}>
          {children}
        </Container>
      </Animated.View>
    </Container>
  );
};

Accordion.propTypes = {
  /**
   * Render a component on the header.
   */
  Header: PropTypes.elementType,
  /**
   * Renders the child component passed in the body of the accordion.
   */
  children: PropTypes.node,
  /**
   * Takes a boolean value based on which border is shown.
   */
  noBorder: PropTypes.bool,
  /**
   * Takes an object based on which the icon to expand/collapse can be customized.
   */
  iconProp: PropTypes.object,
};

```

**Comment by Tsudhishnair** [comment]
@sangameshsomawar 
1. Since all the props inside `iconProp` is for handling Icon/close btn related properties that's why I thought of grouping them together. The individual names like `iconName`, `iconSize` etc can be replaced to just `name`, `size` etc. 

2. We have usecase in neetoDesk where the header component is a textInput, so in such cases where the header has button/input etc adding the onPress on wrapper won't allows us to click on the header component which we are passing. or we can instead of using the touchable component we can use the normal card or View component, then the nested onPress should work.

**Comment by sangameshsomawar** [comment]
@Tsudhishnair  Understood, then just you can improve the documentation and merge.

```
  /**
   * Takes an object based on which the icon to expand/collapse can be customized.
   */
  iconProp: PropTypes.object,
```

**Review by sangameshsomawar — APPROVED** [review]
@Tsudhishnair LGTM now, Merging this PR.

**Pull request merged**
