### PR TITLE
Storybook

### LINKED ISSUE #628: Use Storybook for documentation instead of component-docs
Context: https://github.com/bigbinary/neeto-deploy-web/issues/2286

### PR DESCRIPTION
**Pull request by mohitharshan123**
- Related to #628

### CODE REVIEW

**Comment by mohitharshan123** [comment]
@sangameshsomawar _A Please review

Screenshot 2023-12-11 at 4 38 54 PM

**Review by sangameshsomawar — COMMENTED** [review]
@mohitharshan123 

I think there is a confusion with this task. I thought we are going to move entire documentation to the story book. Like web does, see [this](https://neeto-ui.neeto.com/?path=/docs/components-switch--docs) .

The changes you made are also valid. storybook was working 5-6 months ago, it stopped working in between and now it will get fixed by your changed. But I think Ghouse was asking to move the entire documentation itself to storybook.

@chiraggshah Please clarify

**Comment by sangameshsomawar** [comment]
@mohitharshan123 Getting below error with `yarn storybook`

Screenshot 2023-12-11 at 6 40 01 PM

**Comment by mohitharshan123** [comment]
@sangameshsomawar _A Can you please try now

**Comment by mohitharshan123** [comment]
@sangameshsomawar _A I will move the docs in a separate task

**Comment by sangameshsomawar** [comment]
> @sangameshsomawar _A Can you please try now

@mohitharshan123 I can run. But there are issues with many components. Please test all component once.

1. Card demo looks empty
Screenshot 2023-12-11 at 7 12 25 PM

2. see if font color can be fixed in dark mode 
Screenshot 2023-12-11 at 7 12 43 PM
Screenshot 2023-12-11 at 7 12 54 PM

3. Image component is throwing error 
Screenshot 2023-12-11 at 7 13 27 PM

**Comment by mohitharshan123** [comment]
In order to support docs feature, we have to try with this add on https://www.dannyhwilliams.co.uk/introducing-react-native-web-storybook

**Comment by mohitharshan123** [comment]
@sangameshsomawar I have fixed the components

**Review by sangameshsomawar — APPROVED** [review]
@mohitharshan123 Looks good. 
@chiraggshah Could you please run `yarn storybook` and experience the documentation. To me previous one was looking clean 😄


@mohitharshan123 below are some minor issues:
1. loader is showing black color inside
Screenshot 2023-12-13 at 12 02 19 PM

2.some texts are invisible 
Screenshot 2023-12-13 at 12 02 09 PM

3. Found this bug in controls 
Screenshot 2023-12-13 at 11 59 21 AM

4. Indentation in sample code
Screenshot 2023-12-13 at 11 58 31 AM

**Comment by mohitharshan123** [comment]
@sangameshsomawar Fixed some issues. I tried to disable dark them but it was not working.
Added backgrounds-addon and made it white by default.

**Pull request merged**
