### PR TITLE
fixed text overflow

### PR DESCRIPTION
**Pull request by injas-bigbinary**
@sangameshsomawar _a 
Simulator Screen Shot - iPhone 13 Pro Max - 2022-07-27 at 20 33 51
Simulator Screen Shot - iPhone 13 Pro Max - 2022-07-27 at 20 35 03

Cc: @Tsudhishnair

### CODE REVIEW

**Comment by Tsudhishnair** [comment]
@injas-bigbinary We also need a close icon in the right side of the toast. 
Figma Link: https://www.figma.com/file/GvxNW24y6lmKkrzdZCIz2e/Design-System?node-id=40%3A722
Please refer the screenshot shared below. 

Screenshot 2022-07-27 at 9 35 37 PM

**Review by sangameshsomawar — APPROVED** [review]

**Comment by injas-bigbinary** [comment]
@sangameshsomawar _a Updated

**Comment by Tsudhishnair** [comment]
@injas-bigbinary Just noticed one small thing. The fontSize of the mainText should be `16px` currently its `15px`.
Rest of the changes LGTM.

**Comment by sangameshsomawar** [comment]
@injas-bigbinary _a Please check and merge.

**Comment by injas-bigbinary** [comment]
@Tsudhishnair _a Please check.

**Comment by Tsudhishnair** [comment]
LGTM.

**Pull request merged**
