### PR TITLE
Bottom sheet UI improvements.

### LINKED ISSUE #306: Fix the UI issues for components
- [x] Segment Picker
- [x] Bottom Sheet

### LINKED ISSUE #310: Bottom Sheet UI Improvements.

### PR DESCRIPTION
**Pull request by sangameshsomawar**
partially fixes #306

fixes #310

### CODE REVIEW

**Comment by sangameshsomawar** [comment]
@jenipharachel @injas-bigbinary : https://user-images.githubusercontent.com/93119254/180644216-d90543e2-34b7-453f-a39b-949e0997e0c8.mp4

Please review and merge.

UI Improvements.
1. Rendering children as flat list footer.
2. Default max height is 70%.
3. Used safe area view and removed padding-bottom.
4. Rendering title conditionally.

**Comment by jenipharachel** [comment]
@sangameshsomawar We need to replace Input with SearchBar component. @Tsudhishnair has created a separate component for SearchBar (https://github.com/bigbinary/neeto-ui-rn/blob/master/src/components/SearchBar.js). The state of search value is inside the SearchBar component, We need to move that out to the stories. Can you fix that as well and used the SearchBar component instead of Input.

**Comment by injas-bigbinary** [comment]
@sangameshsomawar Can we make `ContentRow` optional? In neetoInvocie I've faced an issue with the prop. Let me know if any implementation change is required at the project level.

**Comment by sangameshsomawar** [comment]
@injas-bigbinary ContentRow is optional.

**Comment by sangameshsomawar** [comment]
@jenipharachel  Both search bar designs are different right?
Screenshot 2022-07-25 at 12 17 14 PM
Screenshot 2022-07-25 at 12 17 00 PM

**Comment by jenipharachel** [comment]
@sangameshsomawar Sudhish mentioned we can pass autofocus to this component to have Cancel button appear at the right. You can try passing auto focus to the searchbarProps object. (https://github.com/bigbinary/neeto-ui-rn/blob/16297cf324559673b33f5f3b44dc7ecb1337fe31/src/components/SearchBar.js#L96)

Also, we would need to make some changes to the SearchBar component for it to accept the function to close the search bar when Cancel button is clicked in the bottom sheet..

cc: @Tsudhishnair

**Comment by Tsudhishnair** [comment]
@jenipharachel I will create an issue and option to accept function for onClose and onCancel in the searchbar component.

**Comment by sangameshsomawar** [comment]
@jenipharachel: Meanwhile can we merge this?

**Comment by jenipharachel** [comment]
But once the onClose and onCancel changes are done in SearchBar component, then those should be reflected in BottomSheet component as well. Also we won't be giving a release for any app this week. 

@Tsudhishnair How long will it take to make that change in SearchBar component?

**Comment by Tsudhishnair** [comment]
@jenipharachel Apart from the onClose and onCancel function support in the Searchbar component, is there are anything else which is blocking this PR from getting merged.

**Comment by jenipharachel** [comment]
@Tsudhishnair No, that's it. 

@sangameshsomawar  Don't forget to pass the autoFocus prop inside searchbarProps in the bottom sheet component. So, the cancel button will be visible even without the user clicking on the searchBar.

**Comment by Tsudhishnair** [comment]
@jenipharachel I just checked the design and we only have one button in the UI which is the `Cancel` button. So could you tell me what's the requirement of the onClose method in the Searchbar.

**Comment by jenipharachel** [comment]
@Tsudhishnair As I mentioned previously on call, there won't be a need for onClose function.

**Comment by jenipharachel** [comment]
@sangameshsomawar _a Demo: https://youtu.be/xRyv44XexsU
Please review and merge!

**Comment by sangameshsomawar** [comment]
@jenipharachel 
Broken search bar, not able to reproduce every time.
Screenshot 2022-07-26 at 1 24 31 PM

Not able to scroll to extreme down.

https://user-images.githubusercontent.com/93119254/180953784-0fe65e5d-dcf8-4f13-92a7-32f488d809d5.mov

**Comment by jenipharachel** [comment]
@sangameshsomawar Demo: https://youtu.be/MST3MBVdddc. Please review and merge

**Comment by sangameshsomawar** [comment]
@jenipharachel Looks good now. Merging this PR. We can test in neetoInovice.

**Pull request merged**
