### PR TITLE
Added calendar component

### LINKED ISSUE #301: Calendar Component
ref: https://www.figma.com/file/JiKRGmLpkNlVZtbsBIcO1x/neetoInvoice?node-id=95%3A6428

### PR DESCRIPTION
**Pull request by kamolesh97**
closes #301

### CODE REVIEW

**Comment by kamolesh97** [comment]
@sangameshsomawar _a please review and merge.

**Review by sangameshsomawar — APPROVED** [review]
@kamolesh97: Really looks awesome.
I tried removing  key={`${isCurrentDay}  and   and did not face .ssues.
Please tell me and merge.

**Comment by sangameshsomawar** [comment]
@kamolesh97 Fixed merge conflicts and merging this PR as I need it in neetoInvoice.

**Comment by kamolesh97** [comment]
@sangameshsomawar  I'll check if the key is necessary or not anymore, it was needed because the calendar component won't rerender when selected day is not current day, the rerender is needed to change the border color of the current day if it's not selected day.

**Pull request merged**
