### PR TITLE
corrected text overlap and provided dynamic height using padding

### LINKED ISSUE #382: Overlap issue with ListItem component
Ref: https://github.com/bigbinary/neeto-chat-rn/issues/362#issue-1332058493

### PR DESCRIPTION
**Pull request by jenipharachel**
fixes #382 
Screenshot 2022-08-10 at 11 25 44 AM

### CODE REVIEW

**Comment by jenipharachel** [comment]
@sangameshsomawar _a Please review and merge

**Review by sangameshsomawar — APPROVED** [review]
@souravbaranwal LGTM now. merging this PR.

**Comment by sangameshsomawar** [comment]
@jenipharachel Merging this PR, but I am not sure whether 50-50% will work in all scenarios.

**Comment by jenipharachel** [comment]
@sangameshsomawar We can come back and change the width percentage if any issue occurs later.

**Pull request merged**
