### PR TITLE
multi select bottomsheet integration

### PR DESCRIPTION
**Pull request by injas-bigbinary**

### CODE REVIEW

**Comment by injas-bigbinary** [comment]
@sangameshsomawar _a
@Tsudhishnair 

https://user-images.githubusercontent.com/87293196/184830386-ef7d2197-26a7-4219-ae83-39b2a69fa6e6.mp4

**Review by sangameshsomawar — APPROVED** [review]
@injas-bigbinary Code wise looks good. @Tsudhishnair _a  Please review once.
@Tsudhishnair Do we need an event for `onDonePress`  currently we don't have one.

@injas-bigbinary: We have one style issue.
Screenshot 2022-08-16 at 2 10 46 PM

**Comment by injas-bigbinary** [comment]
@sangameshsomawar Updated

Simulator Screen Shot - iPhone 13 Pro Max - 2022-08-16 at 14 48 21

**Comment by Tsudhishnair** [comment]
@sangameshsomawar @injas-bigbinary Currently on clicking done we are just closing the bottomsheet right?
If we are having the `onDonePress` handle then when we can use the same to Post/Fetch the API's when the multi-select action is performed, otherwise on each selection we might have to call the API and re-render the component, which can be avoided if we are having the `onDonePress` handle. 
If we are going forward with having the `onDonePress` handle then what should happen if the user makes few selection and instead of performing `Done` button, clicks on the backdrop. How will that be handled?

**Comment by sangameshsomawar** [comment]
@Tsudhishnair @injas-bigbinary  We can support `onDonePress` then and onBackDropPress should be treated as just hiding. No API calls. Selection will be there but just `onDonePress` should not get called I think. It's not only about the backdrop case, the same question will arise in the case of the android hardware back button.  That's why I think we should just hide it

**Comment by injas-bigbinary** [comment]
@sangameshsomawar Android back button and backdrop are handled through `onRequestClose` prop, right?

**Comment by sangameshsomawar** [comment]
@injas-bigbinary I think its `onBackButtonPress`

**Comment by sangameshsomawar** [comment]
@injas-bigbinary Merging this PR as of now, lets test tomorrow in neetoDesk.

**Pull request merged**
