### PR TITLE
Updated the Searchbar animation logic.

### LINKED ISSUE #445: Cancel button is not rendering properly while animating and cutting in real iPhone XS MAX
https://user-images.githubusercontent.com/93119254/186332972-bdde75f8-190d-463b-96ed-f058b468911f.mov

### PR DESCRIPTION
**Pull request by Tsudhishnair**
Fixes #445 

@sangameshsomawar _a

### CODE REVIEW

**Comment by Tsudhishnair** [comment]
@sangameshsomawar Did you get a chance to check this PR ?

**Comment by sangameshsomawar** [comment]
@Tsudhishnair I have reviewed, Instead of masking the issue, I am thinking to fix with some other approach.  I will debug it by tomorrow EOD.

**Comment by sangameshsomawar** [comment]
@Tsudhishnair  Refactored code and pushed one commit, Please check.

https://user-images.githubusercontent.com/93119254/187617914-32d3a5b0-0aec-4ba8-87db-11d2743a8879.mov

**Comment by Tsudhishnair** [comment]
LGTM.

**Pull request merged**
